import { createHash } from "node:crypto";
import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { resolveClineDataDir } from "@cline/shared/storage";

/**
 * Pi has no built-in tool approval: permission gates are extensions that hook
 * `tool_call` and ask through `ctx.ui.confirm()`. In RPC mode that dialog is
 * emitted on stdout as `extension_ui_request {method:"confirm"}`, which lets the
 * sidecar decide (auto-approve, or show the desktop approval card) and answer
 * with `extension_ui_response`.
 *
 * The extension asks for every tool call; the sidecar answers immediately when
 * the thread auto-approves, so the "ask before running tools" switch can be
 * flipped mid-session without restarting Pi.
 */

/** Marker title the sidecar uses to tell gate prompts apart from other dialogs. */
export const PI_DESKTOP_APPROVAL_TITLE = "pi-desktop:tool-approval";

export const PI_DESKTOP_GATE_EXTENSION_SOURCE = `// Pi Desktop tool-approval gate. Generated by the desktop sidecar; do not edit.
const APPROVAL_TITLE = ${JSON.stringify(PI_DESKTOP_APPROVAL_TITLE)};

export default function piDesktopGate(pi) {
	pi.on("tool_call", async (event, ctx) => {
		if (!ctx.hasUI || ctx.mode !== "rpc") return undefined;
		let payload;
		try {
			payload = JSON.stringify({
				toolCallId: event.toolCallId,
				toolName: event.toolName,
				input: event.input,
			});
		} catch {
			payload = JSON.stringify({
				toolCallId: event.toolCallId,
				toolName: event.toolName,
			});
		}
		const approved = await ctx.ui.confirm(APPROVAL_TITLE, payload);
		if (approved) return undefined;
		return { block: true, reason: "Rejected in Pi Desktop" };
	});
}
`;

export function piDesktopExtensionsDir(): string {
	return join(resolveClineDataDir(), "pi-desktop", "extensions");
}

/**
 * Write the gate extension to a content-addressed path under the desktop data
 * directory and return it. Idempotent; a new sidecar build with different
 * source lands on a new file name, so Pi never loads a stale copy.
 */
export function ensurePiDesktopGateExtension(): string {
	const dir = piDesktopExtensionsDir();
	const hash = createHash("sha256")
		.update(PI_DESKTOP_GATE_EXTENSION_SOURCE)
		.digest("hex")
		.slice(0, 12);
	const path = join(dir, `pi-desktop-gate-${hash}.js`);
	if (existsSync(path)) return path;
	mkdirSync(dir, { recursive: true });
	const tempPath = `${path}.${process.pid}.tmp`;
	writeFileSync(tempPath, PI_DESKTOP_GATE_EXTENSION_SOURCE, "utf8");
	renameSync(tempPath, path);
	return path;
}

export type PiToolApprovalRequest = {
	toolCallId: string;
	toolName: string;
	input?: unknown;
};

/** Parse the gate's confirm payload; null for any other confirm dialog. */
export function parsePiToolApprovalRequest(request: {
	method: string;
	title?: string;
	message?: string;
}): PiToolApprovalRequest | null {
	if (
		request.method !== "confirm" ||
		request.title !== PI_DESKTOP_APPROVAL_TITLE
	) {
		return null;
	}
	try {
		const parsed = JSON.parse(request.message ?? "") as Record<string, unknown>;
		if (!parsed || typeof parsed !== "object") return null;
		return {
			toolCallId:
				typeof parsed.toolCallId === "string" ? parsed.toolCallId : "",
			toolName: typeof parsed.toolName === "string" ? parsed.toolName : "tool",
			input: parsed.input,
		};
	} catch {
		return { toolCallId: "", toolName: "tool" };
	}
}
