import { createHash } from "node:crypto";
import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { resolveClineDataDir } from "@cline/shared/storage";

export const PI_DESKTOP_GATE_EXTENSION_SOURCE = `// Pi Desktop session-tree navigation. Generated by the desktop sidecar; do not edit.

export default function piDesktopGate(pi) {
	// RPC exposes get_tree but not navigate_tree. An extension command is the
	// supported way to invoke Pi's session navigation without starting a turn.
	pi.registerCommand("__pi_desktop_tree_jump", {
		description: "Internal Pi Desktop session-tree navigation",
		handler: async (targetId, ctx) => {
			if (ctx.mode !== "rpc" || !targetId || !/^[a-zA-Z0-9_-]{1,128}$/.test(targetId)) {
				throw new Error("Invalid Pi Desktop tree target");
			}
			if (!ctx.isIdle()) throw new Error("Pi is busy; wait before navigating the tree.");
			const result = await ctx.navigateTree(targetId);
			if (result.cancelled) throw new Error("Pi tree navigation was cancelled by an extension.");
		},
	});
}
`;

export function piDesktopExtensionsDir(): string {
	return join(resolveClineDataDir(), "pi-desktop", "extensions");
}

/**
 * Write the navigation extension to a content-addressed path under the desktop data
 * directory and return it. Idempotent; a new sidecar build with different
 * source lands on a new file name, so Pi never loads a stale copy.
 */
export function ensurePiDesktopGateExtension(): string {
	const dir = piDesktopExtensionsDir();
	const hash = createHash("sha256")
		.update(PI_DESKTOP_GATE_EXTENSION_SOURCE)
		.digest("hex")
		.slice(0, 12);
	const path = join(dir, `pi-desktop-gate-${hash}.js`);
	if (existsSync(path)) return path;
	mkdirSync(dir, { recursive: true });
	const tempPath = `${path}.${process.pid}.tmp`;
	writeFileSync(tempPath, PI_DESKTOP_GATE_EXTENSION_SOURCE, "utf8");
	renameSync(tempPath, path);
	return path;
}
